<?php
/**
 * @file
 * Code for the global_roles feature.
 */

include_once 'global_roles.features.inc';

/**
 * Implements hook_menu().
 *
 * Adds Broken Links menu item to toolbar.
 */
function global_roles_menu() {
  $items['admin/linkchecker'] = array(
    'access arguments' => array('access broken links report'),
    'description' => 'Shows a list of broken links in content.',
    'file' => 'linkchecker.pages.inc',
    'file path' => drupal_get_path('module', 'linkchecker'),
    'page callback' => 'linkchecker_admin_report_page',
    'title' => 'Broken links',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_update_projects_alter().
 */
function global_roles_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['global_roles']);
}

// Adds CSS to Views
/**
 * Implements hook_views_pre_render().
 */
//function global_roles_views_pre_render(&$view) {
//  $global_roles_view = array('global_roles', 'global_roles');
//  if (in_array($view->name, $global_roles_view)) {
//    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
////    $global_roles_module_path = drupal_get_path('module', 'global_roles');
//    //drupal_add_js($contextual_module_path . '/contextual.js');
//    drupal_add_css(drupal_get_path('module', 'global_roles') . '/css/global_roles.css');
//  }
//}


// Adds CSS to view display of page node type but not the edit display
function global_roles_preprocess_page(&$vars) {
  // Global node.
  $node = menu_get_object();
  if (!empty($node) && $node->type == 'page' && arg(2) === null) {
    drupal_add_css(drupal_get_path('module', 'global_roles') . '/css/global_roles.css');
  }
}

// Adding support to discover template files
/**
 * Implements hook_theme_registry_alter()
 **/
function global_roles_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'global_roles');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _global_roles_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 */
function _global_roles_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}